---
# Source: inventory/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: globalid-graphql
  labels:
    app: globalid-graphql
    release: globalid-graphql
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: globalid-graphql
    release: globalid-graphql
